Update KR_Nicaragua_l_english.yml
skullbe/Kaiserreich-Korean-Translation pull request #2380
Opened 2020-01-20 03:37 UTC by attatuirk

2020-01-20 15:04 UTC, gyhs requested changes

2020-01-20 15:04 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Nicaragua_l_english.yml
> +nic.105.t:0 "니카라과 몰락"
니카라과의 몰락

2020-01-20 15:04 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Nicaragua_l_english.yml
> +nic.105.d:0 "니카라과에서 최근 소식이 들어왔습니다. 저들을 상대로 한 전쟁에서 우리가 우위를 점하기 시작한 이래로 니카라과 정부 안에서 벌어진 내분이 점차 커져나갔습니다. 결국 어제 산디노가 공식적으로 니카라과를 떠나 남쪽으로 후퇴하면서 갈등이 정점에 달했습니다. 산디노는 저항을 계속 할 작정입니다. 우리가 받아들인 망명 군대는 이미 수도를 점
니카라과에서 긴급 속보가 들어왔습니다. 우리가 저들을 상대로 전쟁을 벌이고 우위를 점하기 시작한 이후로 니카라과 정부의 내분은 점차 커져나갔습니다. 결국 어제 산디노가 공식적으로 니카라과를 떠나 남쪽으로 후퇴하면서 갈등이 정점에 달했습니다. 산디노는 저항을 계속 할 작정입니다. 우리가 승인한 망명 군대는 이미 수도를 점령했고, 정부를 수립했습니다. 물론 니카라과 내의 저항은... 신 정부에 저항하는 자들이 적다고 말할 수는 없겠습니다. 결국 저들이 자립할 수 있을 때까지 현지 상황을 예의주시해야 합니다.

2020-01-20 15:04 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Nicaragua_l_english.yml
> +nic.108.d:0 "300여명으로 이루어진 소규모 부대로 이루어진 순찰대가 이 나라 남부에서 산디노 군대에게 급습받은 것으로 보입니다. 아직 전투가 진행중이기 때문에 총 손실량은 알 수 없지만, 양측 모두에게 큰 손실을 입히는 피비린내나는 전투가 될 예정입니다. 습격이 진행되는 동안 순찰대가 붕괴되지 않기를 바라고는 있지만, 이건 군대의 능력에 달린
300여명으로 이루어진 소규모 순찰대가 니카라과 남부에서 산디노의 군대에게 급습받은 것으로 보입니다. 아직 전투가 진행중이기 때문에 총 손실은 알 수 없지만, 양측 모두에게 큰 손실을 입히는 피비린내나는 전투가 될 예정입니다. 전투가 진행되는 동안 순찰대가 살아남기를 바라고는 있지만, 이건 순찰대에게 달린 문제입니다.

2020-01-20 15:27 UTC, gyhs commented
제가 맞다면 이걸로 수정해 주세요

2020-01-21 10:25 UTC, attatuirk commented
맞는거 같네요

2020-01-21 10:26 UTC, attatuirk commented
수정했습니다

2020-01-24 13:30 UTC, closed without merging