Update KR_Denmark_l_english.yml
skullbe/Kaiserreich-Korean-Translation pull request #2393
Opened 2020-01-22 16:17 UTC by tjdlsgn98

2020-01-23 15:59 UTC, gyhs requested changes

2020-01-23 15:59 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
> +DEN_idea_infantrybased_military_desc:0 "작은 규모의 국가에서 차량화는 쓸모가 없습니다.: 우리 군대는 어떤 상황이든지 주어진 시간 내에 어디든 도달할 수 있습니다."
우리같이 작은 국가에서 차량화를 사용하는 것은 무의미한 짓입니다. 우리의 군대는 이미 어떠한 상황이든지 주어진 시간 내에 어디든 도달할 수 있습니다.

2020-01-23 15:59 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
> +DEN_idea_motorised_military_desc:0 "현대시대에 알보병은 차량화 보병과 상대가 안됩니다."
현대에 들어와서 보병은 차량화된 보병과 상대가 되지 않습니다.

2020-01-23 15:59 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
> +DEN_idea_flyvevabnet_desc:0 "우리는 적들이 두려워할 수 있도록 육해군의 항공대를 하나의 전문 공군으로 통합했습니다."
우리는 육해군 항공대를 통합하여 적들이 하늘을 두려워하게 해야 합니다.

2020-01-23 15:59 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
> +DEN_idea_flyvevabnet_desc:0 "우리는 적들이 두려워할 수 있도록 육해군의 항공대를 하나의 전문 공군으로 통합했습니다."
맞는것 같다면 바꾸어 주세요

2020-01-23 15:59 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
>  DEN_public_works:0 "공공 공사"
공공 사업

2020-01-23 15:59 UTC, gyhs commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
> +den.45.t:0 "총파업의 종말?"
총파업의 끝?

2020-01-24 13:43 UTC, tjdlsgn98 commented on Kaiserreich Korean Translation/localisation/KR_Denmark_l_english.yml
> +DEN_idea_motorised_military_desc:0 "현대시대에 알보병은 차량화 보병과 상대가 안됩니다."
차량화되지 않은 보병이라는 의미를 부각하기 위해 알보병이란 명칭을 썼어요

2020-01-24 13:44 UTC, tjdlsgn98 commented
수정했습니다

2020-01-25 10:38 UTC, merged